// Generated by CoffeeScript 1.6.3
(function() {
  var Tile, app, parseString, q, request,
    _this = this;

  request = require('request');

  Tile = require('./tile.js').Tile;

  parseString = require('xml2js').parseString;

  app = require('express')();

  console.log('server started! woohoo!');

  this.gridSize = 100;

  q = '<osm-script><query into="_" type="node"><has-kv k="amenity" modv="" v="drinking_water"/><bbox-query e="12.503793239593506" into="_" n="41.8941474761023" s="41.881735516015105" w="12.486820220947266"/></query><print from="_" limit="" mode="body" order="id"/></osm-script>';

  q = '<osm-script>\
  <union into="_"><bbox-query e="7.152" into="_" n="51.251" s="51.249" w="7.148"/><recurse from="_" into="_" type="up"/></union><print from="_" limit="" mode="body" order="id"/></osm-script>';

  console.log(q);

  request.post({
    url: "http://overpass-api.de/api/interpreter",
    body: q
  }, function(err, res, body) {
    return parseString(body, function(err, res) {
      var dater;
      dater = JSON.stringify(res.osm);
      console.log('parsed to xml');
      return process.env.osm = dater;
    });
  });

  app.get('/tile', function(req, res) {
    console.log(process.env.osm);
    res.writeHead(200, {
      'Content-Type': 'application/json'
    });
    return res.end(process.env.osm);
  });

  app.listen(9300);

}).call(this);
