// Generated by CoffeeScript 1.6.3
(function() {
  var Tile, debug, parseString;

  parseString = require('xml2js').parseString;

  debug = require('debug');

  Tile = (function() {
    function Tile(xml) {
      var _this = this;
      this.log = debug('tile');
      this.log('new tile constructed!');
      parseString(xml, function(err, res) {
        _this.osm = res.osm;
        _this.log('parsed to xml');
        _this.json = JSON.stringify(_this.osm);
        _this.log('converted to json');
        return _this.parse();
      });
    }

    Tile.prototype.parse = function() {
      var k, v, _ref, _results;
      _ref = this.osm;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push(console.log(k));
      }
      return _results;
    };

    return Tile;

  })();

  module.exports = {
    Tile: Tile
  };

}).call(this);
